config/routes.rb
IdeaHub::Application.routes.draw do

  resources :ideas do
    resources :links#, shallow: true
  end

  root 'ideas#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base

  validates :title, presence: true
  has_many :links

end

app/models/link.rb
class Link < ActiveRecord::Base

  validates :url, presence: true
  belongs_to :idea

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
  end

  def show
    @idea = Idea.find(params[:id])
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      redirect_to @idea
    else
      flash.now[:errors] = @idea.errors.full_messages
      render @idea
    end
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.try(:update_attributes, idea_params)
      redirect_to @idea
    else
      flash.now[:errors] = @idea.errors.full_messages
      render @idea
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    redirect_to ideas_url
  end

  private
  def idea_params
    params.require(:idea).permit(:title, :why, :copy)
  end

  def link_params
    params.require(:link).permit(:title, :url, :notes, :idea_id)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.where(idea_id: params[:idea_id])
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to @link.idea
    else
      flash.now[:errors] = @idea.errors.full_messages
      render @link.idea
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.try(:update_attributes, link_params)
      redirect_to @link.idea
    else
      flash.now[:errors] = @link.errors.full_messages
      render @link.idea
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    redirect_to @link.idea
  end

  private
  def link_params
    params.require(:link).permit(:title, :url, :notes, :idea_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/ideas/_form.html.erb
<% method = @idea.persisted? ? "PATCH" : "POST" %>
<% action = @idea.persisted? ? idea_url(@idea) : ideas_url  %>
<% title  = @idea.persisted? ? "Edit Idea" : "New Idea" %>
<% submit = @idea.persisted? ? "Update Idea" : "Create Idea" %>

<h1><%= title %></h1>

<form action="<%= action %>" method="<%= method %>" accept-charset="utf-8">
  <input type="hidden" name="authenticity_token" value="" id="<%= form_authenticity_token %>">

  <label>What do you call it?
    <input type="text" name="idea[title]" value="<%= @idea.title %>" id="">
  </label>
  <br>

  <label>What is this solving? What is the customer pain? Describe what this does so well and so much better than others:
    <textarea name="idea[why]" value="<%= @idea.why %>" id="" rows=5 cols=25>What is the purpose of this idea?
    </textarea>
  </label>
  <br>

  <label for="idea_copy">Primary benefit for user:</label>
  <textarea name="idea[copy]" value="<%= @idea.copy %>" id="" rows=5 cols=25>Sell it to me here.

Why should I use this? What does it solve for me?
  </textarea>
  <br>

  <% unless @idea.persisted? %>
    <% 3.times do |i| %>
      <h4>Link</h4>
      <label>Title:
        <input type="text" name="link[title]">
      </label>
      <label>URL:
        <input type="text" name="link[url]">
      <label>
      <br>
      <label>Notes:
        <textarea name="link[notes]">Your comments here...</textarea>
      <label>
    <% end %>
  <% end %>
  <br><br>


  <input type="submit" value="<%= submit %>">
</form>

app/views/ideas/_idea.html.erb
<h1><%= link_to idea.title, idea_url(idea) %></h1>
<ul>
  <li>Problem Solving: <%= idea.why %></li>
  <li>Sell Me on It: <%= idea.copy %></li>
  <li>Links:</li>
  <ul>
    <% idea.links.each do |link| %>
    <li><%= link_to link.title, link.url %></li>
    <li><%= link.notes %></li>
    <% end %>
  </ul>
</ul>

app/views/ideas/edit.html.erb
<%= render 'form' %>

<br>
<%= link_to "Back to Ideas", ideas_url %>

app/views/ideas/index.html.erb
<h1>My Ideas</h1>
<% @ideas.each do |idea| %>
  <%= render idea %>
<% end %>


<%= link_to "Add New Idea", new_idea_url %>

app/views/ideas/new.html.erb
<%= render 'form' %>

<br>
<%= link_to "Back to Ideas", ideas_url %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>

<ul>
  <li>Problem Solving: <%= @idea.why %></li>
  <li>Sell Me on It: <%= @idea.copy %></li>
  <li>Links:</li>
  <ul>
    <% @idea.links.each do |link| %>
    <li><%= link_to link.title, link.url %></li>
    <li><%= link.notes %></li>
    <% end %>
  </ul>
</ul>

<br>
<%= link_to "Back to Ideas", ideas_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaHub</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:success] %>
<%= flash[:errors] %>

<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<h1>Links#edit</h1>
<p>Find me in app/views/links/edit.html.erb</p>

app/views/links/index.html.erb
<h1>Links#index</h1>
<p>Find me in app/views/links/index.html.erb</p>

app/views/links/new.html.erb
<h1>Links#new</h1>
<p>Find me in app/views/links/new.html.erb</p>